import 'server-only';
import type { ContentItem } from './content';
export const items: ContentItem[] = [
  {
    "id": "article-compare-market-research-firms",
    "type": "article",
    "title": "How to compare market research firms",
    "industry": "Professional Services",
    "category": "Research Buying Guide",
    "articleCategory": "Featured Articles",
    "publishDate": "2026-05-03",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1400&q=80",
    "summary": "Compare research partners by method fit, sample quality, fieldwork controls, cost, and decision value.",
    "body": "A practical guide to choosing a research partner for market sizing, customer research, competitive intelligence, voice of customer, pricing studies, expert interviews, and strategy support.",
    "url": "article-compare-market-research-firms.html",
    "slug": "article-compare-market-research-firms"
  },
  {
    "id": "article-market-entry-case",
    "type": "article",
    "title": "How to build a market entry case that leadership can act on",
    "industry": "Automotive & Mobility",
    "category": "Market Strategy",
    "articleCategory": "Featured Articles",
    "publishDate": "2026-04-03",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1400&q=80",
    "summary": "A strong market entry case connects market potential, customer evidence, operating requirements, risk, and investment logic.",
    "body": "Market entry work becomes useful when it moves beyond a market-size slide and gives leadership a clear choice. Start with demand signals, buyer interviews, competitor economics, access constraints, and a realistic view of operating requirements. The final recommendation should explain why now, where to enter first, how to sequence investment, and which risks need active management.",
    "slug": "article-market-entry-case"
  },
  {
    "id": "article-validate-new-market",
    "type": "article",
    "title": "How to validate a new market before committing capital",
    "industry": "BFSI",
    "category": "Market Strategy",
    "articleCategory": "Review Articles",
    "publishDate": "2026-04-24",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1400&q=80",
    "summary": "Use demand signals, competitor economics, buyer interviews, and channel checks to reduce expansion risk.",
    "body": "Useful validation looks at evidence from several angles. Size the reachable opportunity, test buyer urgency, understand competitor economics, map channels, and identify the assumptions that would make the investment unattractive. The goal is not perfect certainty. It is a clear view of what must be true before capital is committed.",
    "slug": "article-validate-new-market"
  },
  {
    "id": "article-strong-voc-programs",
    "type": "article",
    "title": "What strong VoC programs do differently",
    "industry": "Technology & Telecom",
    "category": "Customer Research",
    "articleCategory": "Review Articles",
    "publishDate": "2026-04-21",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=80",
    "summary": "The best programs translate feedback into commercial choices across products, pricing, service, and retention.",
    "body": "Strong Voice of Customer programs begin with decisions, not dashboards. They separate feedback by segment, capture the moments that matter, and connect the findings to product, pricing, service, and customer success actions. A good VoC system helps leaders see which changes will improve retention, conversion, or satisfaction.",
    "slug": "article-strong-voc-programs"
  },
  {
    "id": "article-competitor-scan-questions",
    "type": "article",
    "title": "Five questions every competitor scan should answer",
    "industry": "Technology & Telecom",
    "category": "Competitive Intelligence",
    "articleCategory": "Review Articles",
    "publishDate": "2026-04-18",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=80",
    "summary": "Go beyond company lists by mapping offers, channels, pricing, positioning, partnerships, and operating models.",
    "body": "A competitor scan should explain how rivals win, what customers believe about them, where their economics are strong, and where they are vulnerable. The most useful output is not a profile library. It is a set of strategic implications for product, pricing, channels, partnerships, and positioning.",
    "slug": "article-competitor-scan-questions"
  },
  {
    "id": "article-digital-health-adoption",
    "type": "article",
    "title": "Signals to watch in digital health adoption",
    "industry": "Healthcare",
    "category": "Digital Health",
    "articleCategory": "Latest Release Articles",
    "publishDate": "2026-04-15",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=80",
    "summary": "Track provider workflows, reimbursement clarity, patient repeat usage, and platform integrations to judge momentum.",
    "body": "Digital health momentum is strongest when tools become part of everyday clinical and patient workflows. Adoption signals include repeat patient usage, provider referral behavior, integration with hospital systems, reimbursement clarity, and measurable impact on care navigation or operating efficiency.",
    "slug": "article-digital-health-adoption"
  },
  {
    "id": "article-price-architecture-evidence",
    "type": "article",
    "title": "Why price architecture needs customer evidence",
    "industry": "Consumer & Retail",
    "category": "Pricing",
    "articleCategory": "Review Articles",
    "publishDate": "2026-04-10",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=1400&q=80",
    "summary": "Pricing decisions get sharper when willingness-to-pay data is tied to usage occasions and competitive options.",
    "body": "Price architecture works best when it is grounded in customer evidence. Willingness to pay, perceived value, usage occasions, switching triggers, and competitor alternatives all help teams design tiers that customers understand and sales teams can explain.",
    "slug": "article-price-architecture-evidence"
  },
  {
    "id": "article-supplier-research-negotiation",
    "type": "article",
    "title": "Turning supplier research into negotiation leverage",
    "industry": "Manufacturing",
    "category": "Procurement",
    "articleCategory": "Review Articles",
    "publishDate": "2026-04-08",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=80",
    "summary": "Supplier benchmarking can reveal alternate sources, cost drivers, service tradeoffs, and savings opportunities.",
    "body": "Supplier research creates leverage when it clarifies the market, not just the vendor list. Teams should map credible alternatives, compare service models, understand cost drivers, and identify switching constraints before entering negotiation.",
    "slug": "article-supplier-research-negotiation"
  },
  {
    "id": "article-proptech-market-validation",
    "type": "article",
    "title": "How to validate a proptech market before committing capital",
    "industry": "Real Estate & Construction",
    "category": "Market Validation",
    "articleCategory": "Latest Release Articles",
    "publishDate": "2026-04-29",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80",
    "summary": "Test budget ownership, workflow pain, integration readiness, and channel access before expansion spend is locked.",
    "body": "Proptech validation should begin with the buying workflow. Identify who owns the budget, which operational pain matters most, what integration barriers exist, and which channel partners can accelerate adoption.",
    "slug": "article-proptech-market-validation"
  },
  {
    "id": "article-learner-voc-programs",
    "type": "article",
    "title": "What strong learner VoC programs do differently",
    "industry": "Education & Skilling",
    "category": "Customer Research",
    "articleCategory": "Latest Release Articles",
    "publishDate": "2026-04-27",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=80",
    "summary": "Connect learner motivation, content fit, mentor support, and career outcomes to product decisions.",
    "body": "Learner VoC programs work when they capture feedback at the moments that shape persistence: onboarding, content relevance, support, mentoring, and outcome confidence. The findings should guide program design, support staffing, and partnership decisions.",
    "slug": "article-learner-voc-programs"
  },
  {
    "id": "report-digital-health-platforms",
    "type": "report",
    "title": "India Digital Health Platforms Outlook",
    "industry": "Healthcare",
    "category": "Market Outlook",
    "publishDate": "2026-04-30",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=80",
    "summary": "Adoption drivers, provider workflows, platform economics, and competitive positioning.",
    "body": "This sample report reviews digital health platform adoption, provider workflows, patient behavior, platform economics, and competitive positioning. It helps teams understand where digital care models can scale and where operating constraints remain.",
    "slug": "report-digital-health-platforms"
  },
  {
    "id": "report-ev-charging-middle-east",
    "type": "report",
    "title": "Middle East EV Charging Infrastructure",
    "industry": "Automotive & Mobility",
    "category": "Infrastructure",
    "publishDate": "2026-04-26",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1400&q=80",
    "summary": "Policy support, site economics, operator landscape, and growth scenarios.",
    "body": "The report explores charging demand, policy support, operator models, site economics, and growth scenarios across priority Middle East markets.",
    "slug": "report-ev-charging-middle-east"
  },
  {
    "id": "report-omnichannel-grocery",
    "type": "report",
    "title": "Omnichannel Grocery Market Monitor",
    "industry": "Consumer & Retail",
    "category": "Market Monitor",
    "publishDate": "2026-04-22",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80",
    "summary": "Demand shifts, store formats, delivery economics, loyalty, and pricing trends.",
    "body": "This monitor tracks grocery demand shifts, store formats, delivery economics, private label growth, loyalty programs, and pricing pressure.",
    "slug": "report-omnichannel-grocery"
  },
  {
    "id": "report-enterprise-ai-adoption",
    "type": "report",
    "title": "Enterprise AI Adoption Tracker",
    "industry": "Technology & Telecom",
    "category": "Adoption Tracker",
    "publishDate": "2026-04-19",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=80",
    "summary": "Use cases, budget ownership, vendor shortlists, implementation barriers, and ROI signals.",
    "body": "The tracker maps enterprise AI use cases, buying centers, vendor shortlists, implementation barriers, and ROI proof points.",
    "slug": "report-enterprise-ai-adoption"
  },
  {
    "id": "report-industrial-automation",
    "type": "report",
    "title": "Industrial Automation Opportunity Map",
    "industry": "Manufacturing",
    "category": "Opportunity Map",
    "publishDate": "2026-04-16",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1400&q=80",
    "summary": "Factory digitization, robotics demand, supplier ecosystems, and investment priorities.",
    "body": "This opportunity map reviews robotics, sensors, software, integrators, and automation demand across manufacturing settings.",
    "slug": "report-industrial-automation"
  },
  {
    "id": "report-embedded-finance",
    "type": "report",
    "title": "Embedded Finance Market Review",
    "industry": "BFSI",
    "category": "Market Review",
    "publishDate": "2026-04-12",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1400&q=80",
    "summary": "Partnership models, regulation, user adoption, monetization, and competitive entry routes.",
    "body": "The market review covers embedded finance partnerships, regulatory considerations, monetization models, user adoption, and competitive entry routes.",
    "slug": "report-embedded-finance"
  },
  {
    "id": "report-commercial-assets-demand",
    "type": "report",
    "title": "Commercial Assets Demand Outlook",
    "industry": "Real Estate & Construction",
    "category": "Demand Outlook",
    "publishDate": "2026-05-01",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80",
    "summary": "Tenant demand, occupancy shifts, fit-out cost pressure, and asset repositioning themes.",
    "body": "This outlook reviews commercial asset demand, tenant movement, fit-out cost pressure, asset repositioning, and location priorities.",
    "slug": "report-commercial-assets-demand"
  },
  {
    "id": "report-digital-skilling-platforms",
    "type": "report",
    "title": "Digital Skilling Platform Opportunity Review",
    "industry": "Education & Skilling",
    "category": "Opportunity Review",
    "publishDate": "2026-04-28",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=80",
    "summary": "Learner segments, employer demand, pricing models, and partnership pathways.",
    "body": "The review maps learner segments, employer demand, pricing models, outcomes expectations, and partnership pathways for digital skilling platforms.",
    "slug": "report-digital-skilling-platforms"
  },
  {
    "id": "case-logistics-market-entry",
    "type": "case",
    "title": "Prioritizing six logistics markets for regional expansion",
    "industry": "Automotive & Mobility",
    "category": "Market Entry",
    "publishDate": "2026-04-25",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=80",
    "summary": "Mapped demand density, competitor strength, lane economics, and customer needs to identify the most attractive launch sequence.",
    "body": "DMRK combined demand-density scoring, competitor mapping, customer interviews, and lane economics to prioritize expansion markets. The work helped the client select three pilot markets and define the evidence required before scaling.",
    "slug": "case-logistics-market-entry"
  },
  {
    "id": "case-consumer-pricing-tiers",
    "type": "case",
    "title": "Redesigning price tiers for a consumer services brand",
    "industry": "Consumer & Retail",
    "category": "Pricing",
    "publishDate": "2026-04-20",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=1400&q=80",
    "summary": "Combined willingness-to-pay research with competitor benchmarking to simplify tiers and improve conversion.",
    "body": "The client needed a clearer price ladder. DMRK combined willingness-to-pay research, offer testing, and competitor benchmarking to shape new tiers for phased rollout.",
    "slug": "case-consumer-pricing-tiers"
  },
  {
    "id": "case-supplier-benchmarking",
    "type": "case",
    "title": "Benchmarking suppliers for a high-spend industrial category",
    "industry": "Manufacturing",
    "category": "Procurement",
    "publishDate": "2026-04-17",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1581091215367-59ab6b7e8a9f?auto=format&fit=crop&w=1400&q=80",
    "summary": "Built a supplier universe, compared service models, and identified credible alternatives for negotiation.",
    "body": "DMRK mapped suppliers, compared service models, reviewed cost drivers, and identified credible alternatives that strengthened the client's negotiation position.",
    "slug": "case-supplier-benchmarking"
  },
  {
    "id": "case-b2b-retention-drivers",
    "type": "case",
    "title": "Finding retention drivers for a B2B platform",
    "industry": "Technology & Telecom",
    "category": "Voice of Customer",
    "publishDate": "2026-04-14",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=80",
    "summary": "Surveyed users and interviewed decision makers to isolate onboarding, support, and feature gaps affecting renewal confidence.",
    "body": "The research combined user surveys, buyer interviews, and churn analysis to identify where onboarding, support, and product gaps were affecting renewal confidence.",
    "slug": "case-b2b-retention-drivers"
  },
  {
    "id": "case-construction-materials-growth",
    "type": "case",
    "title": "Prioritizing city clusters for construction materials growth",
    "industry": "Real Estate & Construction",
    "category": "Market Entry",
    "publishDate": "2026-04-29",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1400&q=80",
    "summary": "Used demand-density scoring, channel research, and project pipeline mapping to focus regional expansion.",
    "body": "The client used DMRK's city-cluster scoring to focus expansion on markets with stronger project demand, dealer readiness, and logistics economics.",
    "slug": "case-construction-materials-growth"
  },
  {
    "id": "case-learning-platform-retention",
    "type": "case",
    "title": "Finding retention drivers for a learning platform",
    "industry": "Education & Skilling",
    "category": "Customer Research",
    "publishDate": "2026-04-27",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1400&q=80",
    "summary": "Mapped learner and sponsor feedback to identify onboarding, support, and outcome-signaling gaps.",
    "body": "DMRK interviewed learners, mentors, and employer sponsors to identify renewal drivers and redesign the learner journey around outcome confidence.",
    "slug": "case-learning-platform-retention"
  }
];


export const allItems = [...items].sort((a,b)=>b.publishDate.localeCompare(a.publishDate));
